name: ed_helper_web

description: "Web for Ed - Helper."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  file_picker: ^8.3.1
  audioplayers: ^6.1.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.1
  json_annotation: ^4.9.0
  screenshot: ^3.0.0
  process_run: ^1.2.2+1
  registry: ^0.0.1
  provider: ^6.1.2
  auto_route: ^6.1.0
  custom_mouse_cursor: ^1.1.2
  dio: ^5.8.0+1
  oauth2_client: ^3.3.0
  url_launcher: ^6.3.1
  http: ^1.3.0
  webview_windows: ^0.4.0
  speech_to_text: ^7.0.0
  deepgram_speech_to_text: ^3.0.3
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  screen_retriever: ^0.1.9
  desktop_multi_window: ^0.2.1
  web_socket_channel: ^3.0.2
  audio_waveforms: ^1.2.0
  waveform_flutter: ^1.2.0
  photo_view: ^0.15.0
  flutter_audio_waveforms: ^1.2.1+8
  flutter_sound: ^9.23.1
  args: ^2.6.0
  flutter_markdown: ^0.7.6+2
  flutter_secure_storage: ^9.2.4
  googleapis: ^13.2.0
  google_sign_in: ^6.2.2
  googleapis_auth: ^1.6.0
  video_player: ^2.9.3
  iconsax: ^0.0.8
  file_saver: ^0.2.14
  idb_shim: ^2.0.0
  quickblox_sdk: ^0.16.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  gif_view: ^1.0.0
  encrypt: ^5.0.3
  flutter_riverpod: ^2.6.1
  http_parser: ^4.1.2
  just_audio: ^0.9.46
  universal_html: ^2.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  auto_route_generator: ^6.1.0
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/logo/
    - assets/review_img/
    - .env
flutter_intl:
  enabled: true